### ISSUE TITLE
Deleted and remade files

### ISSUE THREAD

**Issue by mkarpoff** [chrisbra/vim-autoread#1]
If a file is deleted and remade this plugin just starts appending to the end of the current buffer. Would it be possible to make it automatically reload or provide an option to do so?

**Comment by chrisbra** [comment]
don't understand. You have opened a buffer, did `:AutoRead` on it. Then in a shell you removed the file and recreated it. And it keeps appending the content to the current buffer? Isn't that what one usually wants?

I think that is what the `-F` argument to tail does. I could make it configurable.

**Comment by mkarpoff** [comment]
It doesn't clear the current buffer so it esentially becomes both the pre-remade file and the post-remade file concatonated together

**Comment by chrisbra** [comment]
I don't think it is possible to detect that the file essentially changed (it is a different file with the same name). If you have an idea how to do that, let me know.

**Comment by mkarpoff** [comment]
I've looked into this in similar situtations. You could do something like inotify to watch the parent directory for a file change that matches the file name open in vim. That being said I was working in C/C++ so I have no idea how hard that would be in vimscript.

**Comment by chrisbra** [comment]
I think why I initially thought this was a useful behaviour is, that I thought of e.g. logrotate. Does it work, if you use `tail -f`? ( I think it will stop reading the output into the current buffer.

**Comment by chrisbra** [comment]
should be fixed now. I simply compare the filesize. That should work good enough I believe.

**Comment by mkarpoff** [comment]
Works exactly as I hoped. Thank you so much!

**Comment by valerybugakov** [comment]
@chrisbra I'm getting similar behavior, after changing a file in external editor altered content just appends to the existing one. Can I debug/fix it somehow?

```
Plug 'chrisbra/vim-autoread'

au BufEnter * :AutoRead
```

**Comment by valerybugakov** [comment]
@chrisbra I've found the issue, for me it's line 31: https://github.com/chrisbra/vim-autoread/blob/master/autoload/autoread.vim#L31

If I change `<` to `!=` plugin works as expected. But it still appends buffer content instead of replacing it in some cases. For example changing number from 1 to 0 won't change the file size therefore append will be used by autoread plugin.

Is it possible to compare content string by string or using buffer content hash for example? I'm new to vimscript and will be happy to help with that using some tips here :)
